### ISSUE TITLE
useRxData and component re-render

### ISSUE THREAD

**Issue by wnz99** [cvara/rxdb-hooks#17] opened 2020-11-04 08:00 UTC
Apologies if I open a new one, but could now find a way to reopen the previous:

https://github.com/cvara/rxdb-hooks/issues/16

**Comment by cvara** [comment] 2020-11-05 18:50
Closing as duplicate of #16 in favor of transferring any further discussion there.

**Closed by cvara** 2020-11-05 18:50 UTC

**Comment by cvara** [comment] 2020-11-05 18:54
Duplicate of #16
